# Add line numbers on load
addhl global/ number_lines -relative

# Add whitespace chars
addhl global/ show_whitespaces -tab - -tabpad _ -spc ' '

# set color scheme
colorscheme germty

# Set tab options
set-option global indentwidth 0
set-option global tabstop 4

# Add git diff on idle
hook global NormalIdle .* %{git show-diff}

# Add lint on file open and save
hook global WinSetOption filetype=javascript %{
	set buffer lintcmd 'eslint --config $(pwd)/package.json --format=/home/jferrier/node_modules/eslint-formatter-kakoune'
	lint-enable
	lint
	hook buffer BufWritePre .* %{lint}
}

hook global WinSetOption filetype=php %{
	set buffer lintcmd 'node /home/jferrier/kakphplint.js'
	lint-enable
	lint
	hook buffer BufWritePre .* %{lint}
}

# Add some convenience mappings from vim
def sp tmux-new-vertical
def vsp  tmux-new-horizontal
def win tmux-new-window
map global normal <c-e> <c-d>
map global normal <c-y> <c-u>
map global normal <c-p> :find

# Add find functionality
def find -params 1 -shell-candidates %{ find . -type f } %{ edit %arg{1} }

# Add buffer cleanup command (whitespace)
hook global BufWritePre .* %{
	try %{ execute-keys -draft \% <a-s> s \h+$ <ret> d }
	# \% select whole buffer
	# <a-s> split into individual lines
	# s enter search within selection mode
	# \h+$ non return whitespace before \n
	# <ret> d Finish search, then delete selected
}
